#./do_train_single.sh train dutch single 1
#./do_train_single.sh train dutch single 2
#./do_train_single.sh train dutch single 3
#./do_train_single.sh train dutch single 4
#./do_train_single.sh train dutch single 0
#./do_train_single.sh train english single 1
#./do_train_single.sh train english single 2
#./do_train_single.sh train english single 3
#./do_train_single.sh train english single 4
#./do_train_single.sh train english single 0
./do_train_single.sh train french single 1
./do_train_single.sh train french single 2
./do_train_single.sh train french single 3
./do_train_single.sh train french single 4
./do_train_single.sh train french single 0
./do_train_single.sh train italian single 1
./do_train_single.sh train italian single 2
./do_train_single.sh train italian single 3
./do_train_single.sh train italian single 4
./do_train_single.sh train italian single 0
#./do_train_single.sh train german_bert single 1
#./do_train_single.sh train german_bert single 2
#./do_train_single.sh train german_bert single 3
#./do_train_single.sh train german_bert single 4
#./do_train_single.sh train german_bert single 0
#./do_train_single.sh train german_ghisbert single 1
#./do_train_single.sh train german_ghisbert single 2
#./do_train_single.sh train german_ghisbert single 3
#./do_train_single.sh train german_ghisbert single 4
#./do_train_single.sh train german_ghisbert single 0
